name: ndpyramid
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask
  - esmpy>=8.2.0
  - mpich
  - netcdf4
  - numpy
  - pip
  - pooch
  - pre-commit
  - pydantic>=1.10
  - pyproj
  - pytest
  - pytest-cov
  - pytest-mypy
  - rasterio
  - rioxarray
  - scipy
  - sparse>=0.13.0
  - xarray
  - xarray-datatree>=0.0.11
  - xesmf
  - zarr
  - cf_xarray>=0.8.0
  - pip:
      - pytest-codspeed
