name: ndpyramid
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask
  - ipykernel
  - jinja2
  - esmpy>=8.2.0
  - mercantile
  - mpich
  - netcdf4
  - numpy
  - pip
  - pooch
  - pre-commit
  - pydantic>=1.10
  - pyproj
  - pyresample
  - pytest
  - pytest-cov
  - pytest-mypy
  - rasterio
  - rioxarray
  - s3fs
  - scipy
  - sparse>=0.13.0
  - xarray>=2024.10.0
  - xesmf
  - zarr
  - cf_xarray>=0.8.0
  - pip:
      - pytest-codspeed
